name: Astro CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Astro CLI
        run: |
          curl -sSL install.astronomer.io | sudo bash -s

      - name: Dags
        run: |
          cd ${{ github.workspace }}
          astro dev parse
        continue-on-error: false

      - name: Run pytest
        run: |
          cd ${{ github.workspace }}
          astro dev pytest
        continue-on-error: true

      

